Revert "Go preprocessor to find and replace releasetags"
This reverts commit 5e9b9585518c94475f16a2c154ac37200a8af60f.

This change currently causes a crash when building the user guide:

```
2024-05-03 16:55:51 [INFO] (mdbook::book): Book building has started
2024-05-03 16:55:51 [INFO] (mdbook::book): Running the html backend
thread 'main' panicked at '', src/utils/fs.rs:45:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::panicking::panic_display
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:64:5
   3: core::option::expect_failed
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/option.rs:1638:5
   4: <mdbook::renderer::html_handlebars::hbs_renderer::HtmlHandlebars as mdbook::renderer::Renderer>::render
   5: mdbook::book::MDBook::build
   6: mdbook::main
```

Reproducible both locally and in the CI.

Signed-off-by: Dmitry Tantsur <dtantsur@protonmail.com>