Fix virtualized environment
Use /dev/vda instead of /dev/sda in virtualized env
Image provisioning failed: Deploy step deploy.write_image failed on node 7f0be76b-5f79-49ba-bda5-0c153b47b710. No suitable device was found for deployment using these hints {'name': 's== /dev/sda'}

Fix Scenario 2
Error: invalid ControlPlaneMachineCount. Please use a number greater than or equal to 1
Fixed by `--control-plane-machine-count 1`

Image provisioning failed: Deploy step deploy.write_image failed on node 7f0be76b-5f79-49ba-bda5-0c153b47b710.
Download of image CENTOS_9_NODE_IMAGE_K8S_v1.29.0.qcow2 failed:
Unable to write image to /tmp/CENTOS_9_NODE_IMAGE_K8S_v1.29.0.qcow2.
Error: [Errno 28] No space left on device
Fixed by `--ram=8192`

Image provisioning failed: Deploy step deploy.prepare_instance_boot failed:
Failed to install a bootloader when deploying node 7f0be76b-5f79-49ba-bda5-0c153b47b710:
No EFI partition could be detected on device /dev/vda and EFI partition UUID
has not been recorded during deployment (which is often the case for whole disk images).
Are you using a UEFI-compatible image?
Fixed by `bootMode: legacy`

Signed-off-by: Roman Hros <roman.hros@dnation.cloud>